// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	calculator "github.com/ragnaok-iizi/grpc-test/service/grpc/calculator"
	counter "github.com/ragnaok-iizi/grpc-test/service/grpc/counter"
	uploader "github.com/ragnaok-iizi/grpc-test/service/grpc/uploader"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcTestServiceClient is the client API for GrpcTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcTestServiceClient interface {
	Sum(ctx context.Context, in *calculator.CalculatorReq, opts ...grpc.CallOption) (*calculator.CalculatorResp, error)
	Multiply(ctx context.Context, in *calculator.CalculatorReq, opts ...grpc.CallOption) (*calculator.CalculatorResp, error)
	Counter(ctx context.Context, in *counter.CounterReq, opts ...grpc.CallOption) (GrpcTestService_CounterClient, error)
	Uploader(ctx context.Context, opts ...grpc.CallOption) (GrpcTestService_UploaderClient, error)
}

type grpcTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcTestServiceClient(cc grpc.ClientConnInterface) GrpcTestServiceClient {
	return &grpcTestServiceClient{cc}
}

func (c *grpcTestServiceClient) Sum(ctx context.Context, in *calculator.CalculatorReq, opts ...grpc.CallOption) (*calculator.CalculatorResp, error) {
	out := new(calculator.CalculatorResp)
	err := c.cc.Invoke(ctx, "/grpc.GrpcTestService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcTestServiceClient) Multiply(ctx context.Context, in *calculator.CalculatorReq, opts ...grpc.CallOption) (*calculator.CalculatorResp, error) {
	out := new(calculator.CalculatorResp)
	err := c.cc.Invoke(ctx, "/grpc.GrpcTestService/Multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcTestServiceClient) Counter(ctx context.Context, in *counter.CounterReq, opts ...grpc.CallOption) (GrpcTestService_CounterClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrpcTestService_ServiceDesc.Streams[0], "/grpc.GrpcTestService/Counter", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcTestServiceCounterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GrpcTestService_CounterClient interface {
	Recv() (*counter.CounterResp, error)
	grpc.ClientStream
}

type grpcTestServiceCounterClient struct {
	grpc.ClientStream
}

func (x *grpcTestServiceCounterClient) Recv() (*counter.CounterResp, error) {
	m := new(counter.CounterResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcTestServiceClient) Uploader(ctx context.Context, opts ...grpc.CallOption) (GrpcTestService_UploaderClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrpcTestService_ServiceDesc.Streams[1], "/grpc.GrpcTestService/Uploader", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcTestServiceUploaderClient{stream}
	return x, nil
}

type GrpcTestService_UploaderClient interface {
	Send(*uploader.UploaderReq) error
	CloseAndRecv() (*uploader.UploaderResp, error)
	grpc.ClientStream
}

type grpcTestServiceUploaderClient struct {
	grpc.ClientStream
}

func (x *grpcTestServiceUploaderClient) Send(m *uploader.UploaderReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcTestServiceUploaderClient) CloseAndRecv() (*uploader.UploaderResp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(uploader.UploaderResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcTestServiceServer is the server API for GrpcTestService service.
// All implementations must embed UnimplementedGrpcTestServiceServer
// for forward compatibility
type GrpcTestServiceServer interface {
	Sum(context.Context, *calculator.CalculatorReq) (*calculator.CalculatorResp, error)
	Multiply(context.Context, *calculator.CalculatorReq) (*calculator.CalculatorResp, error)
	Counter(*counter.CounterReq, GrpcTestService_CounterServer) error
	Uploader(GrpcTestService_UploaderServer) error
	mustEmbedUnimplementedGrpcTestServiceServer()
}

// UnimplementedGrpcTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcTestServiceServer struct {
}

func (UnimplementedGrpcTestServiceServer) Sum(context.Context, *calculator.CalculatorReq) (*calculator.CalculatorResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedGrpcTestServiceServer) Multiply(context.Context, *calculator.CalculatorReq) (*calculator.CalculatorResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedGrpcTestServiceServer) Counter(*counter.CounterReq, GrpcTestService_CounterServer) error {
	return status.Errorf(codes.Unimplemented, "method Counter not implemented")
}
func (UnimplementedGrpcTestServiceServer) Uploader(GrpcTestService_UploaderServer) error {
	return status.Errorf(codes.Unimplemented, "method Uploader not implemented")
}
func (UnimplementedGrpcTestServiceServer) mustEmbedUnimplementedGrpcTestServiceServer() {}

// UnsafeGrpcTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcTestServiceServer will
// result in compilation errors.
type UnsafeGrpcTestServiceServer interface {
	mustEmbedUnimplementedGrpcTestServiceServer()
}

func RegisterGrpcTestServiceServer(s grpc.ServiceRegistrar, srv GrpcTestServiceServer) {
	s.RegisterService(&GrpcTestService_ServiceDesc, srv)
}

func _GrpcTestService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(calculator.CalculatorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcTestServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GrpcTestService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcTestServiceServer).Sum(ctx, req.(*calculator.CalculatorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcTestService_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(calculator.CalculatorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcTestServiceServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GrpcTestService/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcTestServiceServer).Multiply(ctx, req.(*calculator.CalculatorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcTestService_Counter_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(counter.CounterReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcTestServiceServer).Counter(m, &grpcTestServiceCounterServer{stream})
}

type GrpcTestService_CounterServer interface {
	Send(*counter.CounterResp) error
	grpc.ServerStream
}

type grpcTestServiceCounterServer struct {
	grpc.ServerStream
}

func (x *grpcTestServiceCounterServer) Send(m *counter.CounterResp) error {
	return x.ServerStream.SendMsg(m)
}

func _GrpcTestService_Uploader_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcTestServiceServer).Uploader(&grpcTestServiceUploaderServer{stream})
}

type GrpcTestService_UploaderServer interface {
	SendAndClose(*uploader.UploaderResp) error
	Recv() (*uploader.UploaderReq, error)
	grpc.ServerStream
}

type grpcTestServiceUploaderServer struct {
	grpc.ServerStream
}

func (x *grpcTestServiceUploaderServer) SendAndClose(m *uploader.UploaderResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcTestServiceUploaderServer) Recv() (*uploader.UploaderReq, error) {
	m := new(uploader.UploaderReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcTestService_ServiceDesc is the grpc.ServiceDesc for GrpcTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.GrpcTestService",
	HandlerType: (*GrpcTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _GrpcTestService_Sum_Handler,
		},
		{
			MethodName: "Multiply",
			Handler:    _GrpcTestService_Multiply_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Counter",
			Handler:       _GrpcTestService_Counter_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Uploader",
			Handler:       _GrpcTestService_Uploader_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/service.proto",
}
