// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: grpc/counter/counter.proto

package counter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CounterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *CounterReq) Reset() {
	*x = CounterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_counter_counter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterReq) ProtoMessage() {}

func (x *CounterReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_counter_counter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterReq.ProtoReflect.Descriptor instead.
func (*CounterReq) Descriptor() ([]byte, []int) {
	return file_grpc_counter_counter_proto_rawDescGZIP(), []int{0}
}

func (x *CounterReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type CounterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CounterResp) Reset() {
	*x = CounterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_counter_counter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterResp) ProtoMessage() {}

func (x *CounterResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_counter_counter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterResp.ProtoReflect.Descriptor instead.
func (*CounterResp) Descriptor() ([]byte, []int) {
	return file_grpc_counter_counter_proto_rawDescGZIP(), []int{1}
}

func (x *CounterResp) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_grpc_counter_counter_proto protoreflect.FileDescriptor

var file_grpc_counter_counter_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x38, 0x5a, 0x36,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x67, 0x6e, 0x61,
	0x6f, 0x6b, 0x2d, 0x69, 0x69, 0x7a, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_counter_counter_proto_rawDescOnce sync.Once
	file_grpc_counter_counter_proto_rawDescData = file_grpc_counter_counter_proto_rawDesc
)

func file_grpc_counter_counter_proto_rawDescGZIP() []byte {
	file_grpc_counter_counter_proto_rawDescOnce.Do(func() {
		file_grpc_counter_counter_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_counter_counter_proto_rawDescData)
	})
	return file_grpc_counter_counter_proto_rawDescData
}

var file_grpc_counter_counter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_counter_counter_proto_goTypes = []interface{}{
	(*CounterReq)(nil),  // 0: counter.CounterReq
	(*CounterResp)(nil), // 1: counter.CounterResp
}
var file_grpc_counter_counter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_counter_counter_proto_init() }
func file_grpc_counter_counter_proto_init() {
	if File_grpc_counter_counter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_counter_counter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_counter_counter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_counter_counter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_counter_counter_proto_goTypes,
		DependencyIndexes: file_grpc_counter_counter_proto_depIdxs,
		MessageInfos:      file_grpc_counter_counter_proto_msgTypes,
	}.Build()
	File_grpc_counter_counter_proto = out.File
	file_grpc_counter_counter_proto_rawDesc = nil
	file_grpc_counter_counter_proto_goTypes = nil
	file_grpc_counter_counter_proto_depIdxs = nil
}
